#!/bin/bash
# Sync a lightweight deterministic vector index into Qdrant.

set -euo pipefail

BRAIN_DIR="${BRAIN_DIR:-$HOME/.brain}"
CONFIG_PATH="$BRAIN_DIR/memory/vector-config.json"
INPUT_PATH="${1:-}"

if [ -z "$INPUT_PATH" ] || [ ! -f "$INPUT_PATH" ]; then
  echo "ERROR: provide an index file generated by vector-context-index.sh" >&2
  exit 1
fi

python3 - "$CONFIG_PATH" "$INPUT_PATH" <<'PY'
import hashlib
import json
import math
import pathlib
import re
import sys
import urllib.error
import urllib.request

config_path = pathlib.Path(sys.argv[1])
input_path = pathlib.Path(sys.argv[2])

config = json.loads(config_path.read_text(encoding="utf-8"))
base_url = config["url"].rstrip("/")
collection = config["collection"]
dim = 64

def hashed_embedding(text: str, dim: int = 64):
    vector = [0.0] * dim
    tokens = re.findall(r"[A-Za-z0-9_]{2,}", text.lower())
    if not tokens:
        return vector
    for token in tokens:
        digest = hashlib.sha1(token.encode("utf-8")).hexdigest()
        bucket = int(digest[:8], 16) % dim
        sign = -1.0 if int(digest[8:10], 16) % 2 else 1.0
        vector[bucket] += sign
    norm = math.sqrt(sum(value * value for value in vector)) or 1.0
    return [value / norm for value in vector]

def request(method: str, url: str, payload=None):
    data = None
    headers = {}
    if payload is not None:
      data = json.dumps(payload).encode("utf-8")
      headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    with urllib.request.urlopen(req, timeout=20) as response:
        return response.read().decode("utf-8")

def collection_points_count():
    try:
        response = request("GET", f"{base_url}/collections/{collection}")
        payload = json.loads(response)
        result = payload.get("result", {})
        for key in ("points_count", "vectors_count"):
            value = result.get(key)
            if isinstance(value, int):
                return value
        config = result.get("config", {})
        params = config.get("params", {})
        vectors = params.get("vectors", {})
        if isinstance(vectors, dict) and "size" in vectors:
            return None
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return 0
        raise

try:
    request("DELETE", f"{base_url}/collections/{collection}")
except urllib.error.HTTPError as exc:
    if exc.code != 404:
        raise

try:
    request("GET", f"{base_url}/collections")
    request(
        "PUT",
        f"{base_url}/collections/{collection}",
        {"vectors": {"size": dim, "distance": "Cosine"}},
    )
except urllib.error.HTTPError as exc:
    if exc.code not in (200, 409):
        raise

points = []
for index, line in enumerate(input_path.read_text(encoding="utf-8").splitlines(), start=1):
    if not line.strip():
        continue
    item = json.loads(line)
    points.append(
        {
            "id": index,
            "vector": hashed_embedding(item.get("content", ""), dim=dim),
            "payload": {
                "source_id": item.get("id"),
                "path": item.get("path"),
                "title": item.get("title"),
                "content": item.get("content"),
            },
        }
    )

request(
    "PUT",
    f"{base_url}/collections/{collection}/points?wait=true",
    {"points": points},
)

print(
    json.dumps(
        {
            "provider": config.get("provider", "unknown"),
            "url": base_url,
            "collection": collection,
            "points_written": len(points),
            "points_live": collection_points_count(),
            "status": "live",
        },
        indent=2,
    )
)
PY
