package main

import (
	"context"
	"strings"
	"testing"

	"github.com/reeinharrrd/brain/core/autoevolve"
)

func TestGenerateFromSearch(t *testing.T) {
	gen := NewSkillProposalGenerator(nil)

	t.Run("matches refactor template", func(t *testing.T) {
		artifact := gen.GenerateFromSearch(context.Background(), "refactor auth module", 10, []string{"vscode", "cursor"})
		if artifact == nil {
			t.Fatal("expected artifact, got nil")
		}
		if !strings.Contains(artifact.Draft, "code-refactoring") {
			t.Errorf("expected draft to contain 'code-refactoring', got: %s", artifact.Draft)
		}
		if artifact.Kind != "skill" {
			t.Errorf("expected kind 'skill', got %q", artifact.Kind)
		}
		if artifact.Source != "auto-generated by SkillProposalGenerator" {
			t.Errorf("unexpected source: %q", artifact.Source)
		}
	})

	t.Run("matches debug template", func(t *testing.T) {
		artifact := gen.GenerateFromSearch(context.Background(), "fix nil pointer", 5, []string{"claude"})
		if artifact == nil {
			t.Fatal("expected artifact, got nil")
		}
		if !strings.Contains(artifact.Draft, "debug-session") {
			t.Errorf("expected draft to contain 'debug-session', got: %s", artifact.Draft)
		}
	})

	t.Run("matches test template by example keyword", func(t *testing.T) {
		artifact := gen.GenerateFromSearch(context.Background(), "add tests for auth", 8, []string{"vscode"})
		if artifact == nil {
			t.Fatal("expected artifact, got nil")
		}
		if !strings.Contains(artifact.Draft, "test-generation") {
			t.Errorf("expected draft to contain 'test-generation', got: %s", artifact.Draft)
		}
	})

	t.Run("matches docker template by example keyword", func(t *testing.T) {
		artifact := gen.GenerateFromSearch(context.Background(), "container connection refused", 3, []string{"terminal"})
		if artifact == nil {
			t.Fatal("expected artifact, got nil")
		}
		if !strings.Contains(artifact.Draft, "docker-compose-debug") {
			t.Errorf("expected draft to contain 'docker-compose-debug', got: %s", artifact.Draft)
		}
	})

	t.Run("matches migrate template by example keyword", func(t *testing.T) {
		artifact := gen.GenerateFromSearch(context.Background(), "migrate to new API", 6, []string{"vscode"})
		if artifact == nil {
			t.Fatal("expected artifact, got nil")
		}
		if !strings.Contains(artifact.Draft, "framework-migration") {
			t.Errorf("expected draft to contain 'framework-migration', got: %s", artifact.Draft)
		}
	})

	t.Run("unknown pattern uses generic fallback", func(t *testing.T) {
		artifact := gen.GenerateFromSearch(context.Background(), "some random query xyz", 2, []string{"web"})
		if artifact == nil {
			t.Fatal("expected artifact, got nil")
		}
		if !strings.Contains(artifact.Draft, "generic-skill") {
			t.Errorf("expected draft to contain 'generic-skill' for unknown pattern, got: %s", artifact.Draft)
		}
		if !strings.Contains(artifact.Draft, "general") {
			t.Errorf("expected draft to contain 'general' category, got: %s", artifact.Draft)
		}
	})

	t.Run("includes search count and surfaces in draft", func(t *testing.T) {
		artifact := gen.GenerateFromSearch(context.Background(), "refactor something", 42, []string{"vscode", "cursor", "web"})
		if artifact == nil {
			t.Fatal("expected artifact, got nil")
		}
		if !strings.Contains(artifact.Draft, "42") {
			t.Errorf("expected draft to contain search count 42, got: %s", artifact.Draft)
		}
		if !strings.Contains(artifact.Draft, "vscode") {
			t.Errorf("expected draft to contain surface 'vscode', got: %s", artifact.Draft)
		}
	})

	t.Run("cancelled context returns nil", func(t *testing.T) {
		ctx, cancel := context.WithCancel(context.Background())
		cancel()
		artifact := gen.GenerateFromSearch(ctx, "refactor something", 1, []string{"vscode"})
		if artifact != nil {
			t.Errorf("expected nil for cancelled context, got artifact")
		}
	})
}

func TestGenerateFromFailures(t *testing.T) {
	gen := NewSkillProposalGenerator(nil)

	t.Run("generates proposal from failures", func(t *testing.T) {
		artifact := gen.GenerateFromFailures(context.Background(), "nil pointer dereference", 5)
		if artifact == nil {
			t.Fatal("expected artifact, got nil")
		}
		if artifact.Kind != "skill" {
			t.Errorf("expected kind 'skill', got %q", artifact.Kind)
		}
		if !strings.Contains(artifact.Draft, "nil pointer dereference") {
			t.Errorf("expected draft to contain error type, got: %s", artifact.Draft)
		}
		if !strings.Contains(artifact.Draft, "5") {
			t.Errorf("expected draft to contain failure count, got: %s", artifact.Draft)
		}
	})

	t.Run("debug failure matches debug template", func(t *testing.T) {
		artifact := gen.GenerateFromFailures(context.Background(), "fix nil pointer crash", 3)
		if artifact == nil {
			t.Fatal("expected artifact, got nil")
		}
		if !strings.Contains(artifact.Draft, "debug-session") {
			t.Errorf("expected draft to contain 'debug-session', got: %s", artifact.Draft)
		}
	})

	t.Run("cancelled context returns nil", func(t *testing.T) {
		ctx, cancel := context.WithCancel(context.Background())
		cancel()
		artifact := gen.GenerateFromFailures(ctx, "some error", 1)
		if artifact != nil {
			t.Errorf("expected nil for cancelled context, got artifact")
		}
	})
}

func TestGetTemplates(t *testing.T) {
	t.Run("returns all template names", func(t *testing.T) {
		gen := NewSkillProposalGenerator(nil)
		templates := gen.GetTemplates()

		expectedCount := 5 // refactor, debug, test, docker, migrate
		if len(templates) != expectedCount {
			t.Errorf("expected %d templates, got %d: %v", expectedCount, len(templates), templates)
		}

		// Verify all expected template names are present
		templateSet := make(map[string]bool)
		for _, name := range templates {
			templateSet[name] = true
		}

		expectedNames := []string{"refactor", "debug", "test", "docker", "migrate"}
		for _, name := range expectedNames {
			if !templateSet[name] {
				t.Errorf("expected template %q not found", name)
			}
		}
	})
}

func TestNilTelemetryHandling(t *testing.T) {
	t.Run("nil telemetry does not panic", func(t *testing.T) {
		gen := NewSkillProposalGenerator(nil)
		// Should not panic
		artifact := gen.GenerateFromSearch(context.Background(), "test query", 1, []string{"vscode"})
		if artifact == nil {
			t.Fatal("expected artifact, got nil")
		}
	})

	t.Run("nil telemetry GetTemplates does not panic", func(t *testing.T) {
		gen := NewSkillProposalGenerator(nil)
		templates := gen.GetTemplates()
		if len(templates) == 0 {
			t.Error("expected templates to be populated even with nil telemetry")
		}
	})
}

func TestSkillTemplateStruct(t *testing.T) {
	t.Run("default templates have required fields", func(t *testing.T) {
		for name, tmpl := range defaultSkillTemplates {
			if tmpl.Name == "" {
				t.Errorf("template %q has empty Name", name)
			}
			if tmpl.Category == "" {
				t.Errorf("template %q has empty Category", name)
			}
			if len(tmpl.Steps) == 0 {
				t.Errorf("template %q has no Steps", name)
			}
			// Prerequisites and Examples can be empty
		}
	})

	t.Run("refactor template has prerequisites", func(t *testing.T) {
		tmpl := defaultSkillTemplates["refactor"]
		if len(tmpl.Prerequisites) == 0 {
			t.Error("refactor template should have prerequisites")
		}
	})

	t.Run("all templates have at least one example", func(t *testing.T) {
		for name, tmpl := range defaultSkillTemplates {
			if len(tmpl.Examples) == 0 {
				t.Errorf("template %q has no examples", name)
			}
		}
	})
}

func TestMatchTemplate(t *testing.T) {
	gen := NewSkillProposalGenerator(nil)

	t.Run("pattern match takes precedence", func(t *testing.T) {
		// The refactor template has empty Pattern field, so it won't match by pattern.
		// But it should match by example keywords.
		tmpl := gen.matchTemplate("refactor this code please")
		if tmpl.Name != "code-refactoring" {
			t.Errorf("expected code-refactoring, got %q", tmpl.Name)
		}
	})

	t.Run("unknown query returns generic", func(t *testing.T) {
		tmpl := gen.matchTemplate("zxcvbnm random gibberish")
		if tmpl.Name != "generic-skill" {
			t.Errorf("expected generic-skill, got %q", tmpl.Name)
		}
		if tmpl.Category != "general" {
			t.Errorf("expected general category, got %q", tmpl.Category)
		}
	})
}

// Verify autoevolve.ProposedArtifact fields are accessible
func TestProposedArtifactFields(t *testing.T) {
	t.Run("artifact has all expected fields", func(t *testing.T) {
		artifact := &autoevolve.ProposedArtifact{
			Kind:   "skill",
			ID:     "test-123",
			Draft:  "# Test",
			Source: "test",
		}
		if artifact.Kind != "skill" {
			t.Errorf("expected kind 'skill', got %q", artifact.Kind)
		}
		if artifact.ID != "test-123" {
			t.Errorf("expected ID 'test-123', got %q", artifact.ID)
		}
		if artifact.Draft != "# Test" {
			t.Errorf("expected draft '# Test', got %q", artifact.Draft)
		}
		if artifact.Source != "test" {
			t.Errorf("expected source 'test', got %q", artifact.Source)
		}
	})
}
