package main

import (
	"context"
	"fmt"
	"strings"

	"github.com/reeinharrrd/brain/core/autoevolve"
)

// SkillTemplate defines a skill template
type SkillTemplate struct {
	Name          string
	Pattern       string // search pattern that triggered this
	Category      string
	Steps         []string
	Prerequisites []string
	Examples      []string
}

// SkillProposalGenerator generates skill proposals from patterns
type SkillProposalGenerator struct {
	telemetry *autoevolve.TelemetryAccumulator
	templates map[string]*SkillTemplate
}

// NewSkillProposalGenerator creates a new SkillProposalGenerator
func NewSkillProposalGenerator(telemetry *autoevolve.TelemetryAccumulator) *SkillProposalGenerator {
	templates := make(map[string]*SkillTemplate, len(defaultSkillTemplates))
	for k, v := range defaultSkillTemplates {
		templates[k] = v
	}
	return &SkillProposalGenerator{
		telemetry: telemetry,
		templates: templates,
	}
}

// GenerateFromSearch creates a skill proposal based on search patterns
func (g *SkillProposalGenerator) GenerateFromSearch(ctx context.Context, query string, searchCount int, surfaces []string) *autoevolve.ProposedArtifact {
	if err := ctx.Err(); err != nil {
		return nil
	}

	template := g.matchTemplate(query)

	steps := template.Steps
	if steps == nil {
		steps = []string{
			"Analyze the problem domain",
			"Gather requirements and constraints",
			"Design the solution approach",
			"Implement the solution",
			"Test and verify correctness",
		}
	}

	prereqs := template.Prerequisites
	if prereqs == nil {
		prereqs = []string{}
	}

	category := template.Category
	if category == "" {
		category = "general"
	}

	prereqText := ""
	if len(prereqs) > 0 {
		prereqText = "\n\nPrerequisites: " + strings.Join(prereqs, ", ")
	}

	draft := fmt.Sprintf(`# Skill: %s

Category: %s

Triggered by search pattern: %q (searched %d times)
Surfaces: %v
%s

## Steps

`, template.Name, category, query, searchCount, surfaces, prereqText)

	for i, step := range steps {
		draft += fmt.Sprintf("%d. %s\n", i+1, step)
	}

	return &autoevolve.ProposedArtifact{
		Kind:   "skill",
		ID:     fmt.Sprintf("skill-%s", template.Name),
		Draft:  draft,
		Source: "auto-generated by SkillProposalGenerator",
	}
}

// GenerateFromFailures creates a skill proposal based on failure patterns
func (g *SkillProposalGenerator) GenerateFromFailures(ctx context.Context, errorType string, count int) *autoevolve.ProposedArtifact {
	if err := ctx.Err(); err != nil {
		return nil
	}

	template := g.matchTemplate(errorType)

	steps := template.Steps
	if steps == nil {
		steps = []string{
			"Collect error messages and stack traces",
			"Identify root cause through systematic investigation",
			"Propose and implement fix",
			"Add regression test",
			"Verify fix in production",
		}
	}

	category := template.Category
	if category == "" {
		category = "general"
	}

	draft := fmt.Sprintf(`# Skill: %s

Category: %s

Triggered by failure pattern: %q (failed %d times)

## Steps

`, template.Name, category, errorType, count)

	for i, step := range steps {
		draft += fmt.Sprintf("%d. %s\n", i+1, step)
	}

	return &autoevolve.ProposedArtifact{
		Kind:   "skill",
		ID:     fmt.Sprintf("skill-%s-fix", template.Name),
		Draft:  draft,
		Source: "auto-generated by SkillProposalGenerator",
	}
}

// GetTemplates returns all available template names
func (g *SkillProposalGenerator) GetTemplates() []string {
	names := make([]string, 0, len(g.templates))
	for name := range g.templates {
		names = append(names, name)
	}
	return names
}

// matchTemplate finds the best matching template for a query
func (g *SkillProposalGenerator) matchTemplate(query string) *SkillTemplate {
	queryLower := strings.ToLower(query)

	// Try exact pattern match first
	for _, t := range g.templates {
		if t.Pattern != "" && strings.Contains(queryLower, strings.ToLower(t.Pattern)) {
			return t
		}
	}

	// Try matching by example keywords
	for _, t := range g.templates {
		for _, example := range t.Examples {
			if strings.Contains(queryLower, strings.ToLower(example)) {
				return t
			}
		}
	}

	// Try matching by template name keywords
	for _, t := range g.templates {
		nameLower := strings.ToLower(t.Name)
		// Extract keywords from template name
		keywords := strings.Split(nameLower, "-")
		for _, kw := range keywords {
			if len(kw) > 2 && strings.Contains(queryLower, kw) {
				return t
			}
		}
	}

	// Generic fallback
	return &SkillTemplate{
		Name:     "generic-skill",
		Category: "general",
		Steps: []string{
			"Analyze the problem domain",
			"Gather requirements and constraints",
			"Design the solution approach",
			"Implement the solution",
			"Test and verify correctness",
		},
		Prerequisites: []string{},
		Examples:      []string{},
	}
}

// Default skill templates
var defaultSkillTemplates = map[string]*SkillTemplate{
	"refactor": {
		Name:     "code-refactoring",
		Category: "development",
		Steps: []string{
			"Analyze current code structure",
			"Identify code smells and anti-patterns",
			"Plan refactoring approach",
			"Implement changes incrementally",
			"Verify behavior unchanged with tests",
		},
		Prerequisites: []string{"language:go or language:typescript"},
		Examples:      []string{"refactor auth module", "clean up API handlers"},
	},
	"debug": {
		Name:     "debug-session",
		Category: "development",
		Steps: []string{
			"Reproduce the issue",
			"Collect error messages and stack traces",
			"Identify root cause through systematic investigation",
			"Propose and implement fix",
			"Add regression test",
		},
		Prerequisites: []string{},
		Examples:      []string{"fix nil pointer", "debug crash on startup"},
	},
	"test": {
		Name:     "test-generation",
		Category: "development",
		Steps: []string{
			"Identify untested code paths",
			"Write unit tests for core logic",
			"Write integration tests for boundaries",
			"Add edge case coverage",
			"Verify test suite passes",
		},
		Prerequisites: []string{},
		Examples:      []string{"add tests for auth", "cover edge cases in parser"},
	},
	"docker": {
		Name:     "docker-compose-debug",
		Category: "infrastructure",
		Steps: []string{
			"Check container status and logs",
			"Verify network configuration",
			"Test service dependencies",
			"Apply fix and restart services",
			"Verify full stack health",
		},
		Prerequisites: []string{"docker", "docker-compose"},
		Examples:      []string{"docker compose not starting", "container connection refused"},
	},
	"migrate": {
		Name:     "framework-migration",
		Category: "development",
		Steps: []string{
			"Inventory current usage of old framework",
			"Map to equivalent in new framework",
			"Migrate files incrementally",
			"Update imports and dependencies",
			"Run full test suite",
		},
		Prerequisites: []string{},
		Examples:      []string{"migrate to new API", "update from v1 to v2"},
	},
}
