package autoevolve

import (
	"context"
	"fmt"
	"sort"
	"sync"
	"time"
)

// AnalysisReport is the full analysis result
type AnalysisReport struct {
	Period           time.Time
	TopSkills        []SkillUsage
	FailedSkills     []SkillUsage
	MissingSkills    []MissingSkill
	TokenWaste       []TokenWasteFinding
	MCPPatterns      []MCPPattern
	PolicyViolations []PolicyViolation
	Recommendations  []Recommendation
}

// SkillUsage tracks how a skill is used
type SkillUsage struct {
	ID          string
	Activations int
	SuccessRate float64
	AvgDuration time.Duration
	AvgTokens   int
}

// MissingSkill represents a frequently-searched-but-not-found skill
type MissingSkill struct {
	Query       string
	SearchCount int
	TopSurfaces []string
}

// TokenWasteFinding identifies token waste
type TokenWasteFinding struct {
	Surface     string
	WasteRate   float64
	TotalWasted int
	Description string
}

// MCPPattern tracks MCP usage
type MCPPattern struct {
	ServerID    string
	Calls       int
	SuccessRate float64
	AvgLatency  time.Duration
}

// PolicyViolation tracks policy enforcement
type PolicyViolation struct {
	Rule     string
	Count    int
	Severity string
	Surfaces []string
}

// Recommendation is an improvement proposal
type Recommendation struct {
	Type              string  // new_skill, update_skill, deprecate_skill, new_mcp, optimize_context
	Title             string
	Description       string
	Evidence          []UsageTelemetry
	Impact            string  // high, medium, low
	Effort            string  // trivial, small, medium, large
	Confidence        float64 // 0.0-1.0
	ProposedArtifact  *ProposedArtifact // If applicable
	Approved          *bool   // nil=pending
}

// ProposedArtifact is a draft artifact
type ProposedArtifact struct {
	Kind   string // skill, mcp, rule
	ID     string
	Draft  string // Markdown draft
	Source string // "auto-generated by AutoEvolve"
}

// Analyzer runs periodic analysis
type Analyzer struct {
	telemetry *TelemetryAccumulator
	mu        sync.Mutex
	reports   []*AnalysisReport
}

func NewAnalyzer(telemetry *TelemetryAccumulator) *Analyzer {
	return &Analyzer{
		telemetry: telemetry,
		reports:   make([]*AnalysisReport, 0),
	}
}

func (a *Analyzer) Analyze(ctx context.Context) (*AnalysisReport, error) {
	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("analyze: %w", err)
	}

	report := &AnalysisReport{
		Period: time.Now(),
	}

	// 1. Collect telemetry data (already in accumulator)
	events := a.telemetry.GetEvents(ctx)

	// 2. Identify top N skills (by activation count)
	report.TopSkills = a.getTopSkills(ctx)

	// 3. Identify failed skills (>30% failure rate)
	report.FailedSkills = a.getFailedSkills(ctx)

	// 4. Detect missing skills (searches with no results, count >= 5)
	report.MissingSkills = a.getMissingSkills(ctx)

	// 5. Find token waste (waste rate > 50%)
	report.TokenWaste = a.getTokenWaste(ctx)

	// 6. Generate recommendations based on findings
	a.generateRecommendations(ctx, report, events)

	// 7. Store report
	a.mu.Lock()
	a.reports = append(a.reports, report)
	a.mu.Unlock()

	return report, nil
}

func (a *Analyzer) GetReports(ctx context.Context) []*AnalysisReport {
	if err := ctx.Err(); err != nil {
		return nil
	}

	a.mu.Lock()
	defer a.mu.Unlock()

	result := make([]*AnalysisReport, len(a.reports))
	copy(result, a.reports)
	return result
}

func (a *Analyzer) getTopSkills(ctx context.Context) []SkillUsage {
	failureStats := a.telemetry.GetFailureStats(ctx)
	events := a.telemetry.GetEvents(ctx)

	// Aggregate by artifactID
	type skillAcc struct {
		activations int
		successes   int
		totalDur    time.Duration
		totalTokens int
	}

	accMap := make(map[string]*skillAcc)

	for _, e := range events {
		if e.ArtifactID == "" || e.ArtifactKind != "skill" {
			continue
		}
		s, ok := accMap[e.ArtifactID]
		if !ok {
			s = &skillAcc{}
			accMap[e.ArtifactID] = s
		}
		s.activations++
		if e.Success {
			s.successes++
		}
		s.totalDur += e.Duration
		s.totalTokens += e.TokensUsed
	}

	var result []SkillUsage
	for id, s := range accMap {
		su := SkillUsage{
			ID:          id,
			Activations: s.activations,
			AvgDuration: s.totalDur / time.Duration(s.activations),
			AvgTokens:   s.totalTokens / s.activations,
		}
		if s.activations > 0 {
			su.SuccessRate = float64(s.successes) / float64(s.activations)
		}
		// Override with failure stats if available
		if fs, ok := failureStats[id]; ok {
			su.SuccessRate = 1.0 - fs.FailureRate
		}
		result = append(result, su)
	}

	// Sort by activation count descending
	sort.Slice(result, func(i, j int) bool {
		return result[i].Activations > result[j].Activations
	})

	return result
}

func (a *Analyzer) getFailedSkills(ctx context.Context) []SkillUsage {
	failureStats := a.telemetry.GetFailureStats(ctx)

	var result []SkillUsage
	for id, fs := range failureStats {
		if fs.FailureRate > 0.3 && fs.TotalAttempts > 0 {
			result = append(result, SkillUsage{
				ID:          id,
				Activations: fs.TotalAttempts,
				SuccessRate: 1.0 - fs.FailureRate,
			})
		}
	}

	sort.Slice(result, func(i, j int) bool {
		return result[i].SuccessRate < result[j].SuccessRate
	})

	return result
}

func (a *Analyzer) getMissingSkills(ctx context.Context) []MissingSkill {
	gapStats := a.telemetry.GetGapStats(ctx)

	var result []MissingSkill
	for _, gs := range gapStats {
		if gs.SearchCount >= 5 {
			surfaces := make([]string, 0, len(gs.TopSurfaces))
			for s := range gs.TopSurfaces {
				surfaces = append(surfaces, s)
			}
			result = append(result, MissingSkill{
				Query:       gs.Query,
				SearchCount: gs.SearchCount,
				TopSurfaces: surfaces,
			})
		}
	}

	sort.Slice(result, func(i, j int) bool {
		return result[i].SearchCount > result[j].SearchCount
	})

	return result
}

func (a *Analyzer) getTokenWaste(ctx context.Context) []TokenWasteFinding {
	wasteStats := a.telemetry.GetWasteStats(ctx)

	var result []TokenWasteFinding
	for surface, ws := range wasteStats {
		if ws.WasteRate > 0.5 {
			result = append(result, TokenWasteFinding{
				Surface:     surface,
				WasteRate:   ws.WasteRate,
				TotalWasted: ws.TotalWasted,
				Description: fmt.Sprintf("Surface %q has %.0f%% token waste rate (%d wasted tokens across %d sessions)",
					surface, ws.WasteRate*100, ws.TotalWasted, ws.Sessions),
			})
		}
	}

	sort.Slice(result, func(i, j int) bool {
		return result[i].WasteRate > result[j].WasteRate
	})

	return result
}

func (a *Analyzer) generateRecommendations(ctx context.Context, report *AnalysisReport, events []UsageTelemetry) {
	// Recommend creating new skills for frequently searched missing skills
	for _, ms := range report.MissingSkills {
		rec := Recommendation{
			Type:        "new_skill",
			Title:       fmt.Sprintf("Create skill for %q", ms.Query),
			Description: fmt.Sprintf("Users searched for %q %d times without finding a result. Top surfaces: %v",
				ms.Query, ms.SearchCount, ms.TopSurfaces),
			Impact:     "high",
			Effort:     "medium",
			Confidence: 0.8,
			ProposedArtifact: &ProposedArtifact{
				Kind:   "skill",
				ID:     fmt.Sprintf("auto-%s", ms.Query),
				Draft:  fmt.Sprintf("# Skill: %s\n\nAuto-generated skill proposal for frequently searched term.\n", ms.Query),
				Source: "auto-generated by AutoEvolve",
			},
		}
		report.Recommendations = append(report.Recommendations, rec)
	}

	// Recommend updating failed skills
	for _, fs := range report.FailedSkills {
		rec := Recommendation{
			Type:        "update_skill",
			Title:       fmt.Sprintf("Improve reliability of skill %q", fs.ID),
			Description: fmt.Sprintf("Skill %q has a %.0f%% success rate across %d activations",
				fs.ID, fs.SuccessRate*100, fs.Activations),
			Impact:     "high",
			Effort:     "medium",
			Confidence: 0.7,
		}
		report.Recommendations = append(report.Recommendations, rec)
	}

	// Recommend optimizing contexts for high waste
	for _, tw := range report.TokenWaste {
		rec := Recommendation{
			Type:        "optimize_context",
			Title:       fmt.Sprintf("Reduce token waste on %q", tw.Surface),
			Description: tw.Description,
			Impact:      "medium",
			Effort:      "small",
			Confidence:  0.6,
		}
		report.Recommendations = append(report.Recommendations, rec)
	}

	// If there are top skills with high usage, recommend keeping them
	// If there are skills with zero usage that exist, recommend deprecation
	// (Simplified: recommend deprecating skills with very low usage and high failure)
	for _, fs := range report.FailedSkills {
		if fs.Activations < 5 {
			rec := Recommendation{
				Type:        "deprecate_skill",
				Title:       fmt.Sprintf("Consider deprecating skill %q", fs.ID),
				Description: fmt.Sprintf("Skill %q has low usage (%d activations) and high failure rate (%.0f%%)",
					fs.ID, fs.Activations, (1.0-fs.SuccessRate)*100),
				Impact:     "low",
				Effort:     "trivial",
				Confidence: 0.5,
			}
			report.Recommendations = append(report.Recommendations, rec)
		}
	}
}
